sudo: true
dist: trusty

install:
  - sudo apt-get --yes install snapd
  - sudo snap install hugo

script:
  - /snap/bin/hugo 

deploy:
  provider: pages
  local-dir: public
  repo: kanekotic/kanekotic.github.com
  target-branch: master
  skip-cleanup: true
  email: $GITHUB_EMAIL
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
