baseURL = "https://www.kanekotic.com/"
languageCode = "en-en"
title = "Kanekotic's Page"
theme = "github-style"
googleAnalytics = ""
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Kanekotic"
  description = "Code for living, fun and the lulz. I spend the day thinking what things can make my life easier, automating things allowing me to enjoy a moment of Laziness. Then is just hours of implementation to be able to share them with the community, because there is no value if the only one that can enjoy something is me."
  github = "kanekotic"
  twitter = "kanekotic"
  linkedin = "kanekotic"
  email = ""
  url = "https://www.kanekotic.com"
  keywords = ""
  rss = true
  lastmod = true
  userStatusEmoji = "😀"
  favicon = "/images/github.png"
  location = "Spain"

#  [[params.links]]
#    title = "Link"
#    href = "https://github.com/meik2333"
#  [[params.links]]
#    title = "Link2"
#    href = "https://meik2333.com"
#    icon = "https://meik2333.com/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
