---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: blog
  label: Blog
  create: all
  match: "**/*"
  templates:
  - blog-post
- type: directory
  path: integrations/hashnode
  label: Hashnode
  create: all
  match: "**/*"
  templates:
  - hashnode-post
- type: directory
  path: docs
  label: Projects
  create: all
  match: "**/*"
  templates:
  - project
upload_dir: static/img
public_path: https://www.kanekotic.com/img
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: build
  install_dependencies_command: yarn install
  preview_docker_image: node:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn start
