backend:
  name: github
  repo: kanekotic/kanekotic-page
  branch: main
  site_domain: gifted-allen-42e579.netlify.app

media_folder: 'static/images/'
public_folder: 'images'
collections:
  - name: posts
    label: Posts
    label_singular: Post
    folder: 'content/post'
    path: '{{slug}}/index'
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Publish this page on", name: "date", widget: "datetime"}
      - {label: "Is draft in kanekotic.com", name: "draft", widget: "boolean", default: false}
      - {label: "Publish to Dev.to", name: "published", widget: "boolean", default: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - label: "Featured Image"
        name: "image"
        required: false
        widget: object
        fields:
          - label: "Upload an image named `featured.jpg/png`"
            name: "filename"
            widget: "image"
            default: "featured"
            media_library:
              config:
                multiple: false
          - {label: Caption, name: caption, widget: string, required: false}
          - {label: Description for screen readers, name: alt_text, widget: string, required: false}
          - {label: "Where's the focal point in the image? Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.", name: focal_point, widget: string, required: false, default: "Smart"}
          - {label: Thumbnail Only?, name: preview_only, widget: boolean, default: false}
      - {label: "Body", name: "body", widget: "markdown"}